export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAIL = 'CREATE_APPOINTMENT_FAIL';

export const GET_APPOINTMENT_REQUEST = 'GET_APPOINTMENT_REQUEST';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAIL = 'GET_APPOINTMENT_FAIL';
export const GET_APPOINTMENT_RESET = 'GET_APPOINTMENT_RESET';

export const GET_BUSINESS_APPOINTMENT_REQUEST =
  'GET_BUSINESS_APPOINTMENT_REQUEST ';
export const GET_BUSINESS_APPOINTMENT_SUCCESS =
  'GET_BUSINESS_APPOINTMENT_SUCCESS';
export const GET_BUSINESS_APPOINTMENT_FAIL = 'GET_BUSINESS_APPOINTMENT_FAIL';

export const GET_USER_APPOINTMENT_REQUEST = 'GET_USER_APPOINTMENT_REQUEST';
export const GET_USER_APPOINTMENT_SUCCESS = 'GET_USER_APPOINTMENT_SUCCESS';
export const GET_USER_APPOINTMENT_FAIL = 'GET_USER_APPOINTMENT_FAIL';
export const GET_USER_APPOINTMENT_RESET = 'GET_USER_APPOINTMENT_RESET';

export const DELETE_APPOINTMENT_REQUEST = 'DELETE_APPOINTMENT_REQUEST';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FAIL = 'DELETE_APPOINTMENT_FAIL';
export const DELETE_APPOINTMENT_RESET = 'DELETE_APPOINTMENT_RESET';

// ADMIN
export const GET_ADMIN_APPOINTMENT_REQUEST = 'GET_ADMIN_APPOINTMENT_REQUEST';
export const GET_ADMIN_APPOINTMENT_SUCCESS = 'GET_ADMIN_APPOINTMENT_SUCCESS';
export const GET_ADMIN_APPOINTMENT_FAIL = 'GET_ADMIN_APPOINTMENT_FAIL';

export const UPDATE_APPOINTMENT_APPROVAL = 'UPDATE_APPOINTMENT_APPROVAL';
