export const GET_ALL_BUSINESS_REQUEST = 'GET_ALL_BUSINESS_REQUEST ';
export const GET_ALL_BUSINESS_SUCCESS = 'GET_ALL_BUSINESS_SUCCESS';
export const GET_ALL_BUSINESS_FAIL = 'GET_ALL_BUSINESS_FAIL';

export const GET_SINGLE_BUSINESS_REQUEST = 'GET_SINGLE_BUSINESS_REQUEST';
export const GET_SINGLE_BUSINESS_SUCCESS = 'GET_SINGLE_BUSINESS_SUCCESS';
export const GET_SINGLE_BUSINESS_FAIL = 'GET_SINGLE_BUSINESS_FAIL';

export const UPDATE_BUSINESS_REQUEST = 'UPDATE_BUSINESS_REQUEST';
export const UPDATE_BUSINESS_SUCCESS = 'UPDATE_BUSINESS_SUCCESS';
export const UPDATE_BUSINESS_FAIL = 'UPDATE_BUSINESS_FAIL';
