export const GET_USER_SERVICE_REQUEST = 'GET_USER_SERVICE_REQUEST ';
export const GET_USER_SERVICE_SUCCESS = 'GET_USER_SERVICE_SUCCESS';
export const GET_USER_SERVICE_FAIL = 'GET_USER_SERVICE_FAIL';
export const GET_USER_SERVICE_RESET = 'GET_USER_SERVICE_RESET';
